# Generated by Django 3.0.2 on 2020-01-09 20:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200109_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
